### ISSUE TITLE
Transform2D branch: Nesting transforms skewing issue

### ISSUE THREAD

**Issue by robsilv** [CadetEditor/CadetEngine-as#10]
In the editor, create 2 rectangle components.
Now nest the second within the first.
Set the scaleX property of the parent rectangle to 3.
Rotate the parent transform using the rotation slider, note how neither the parent or child transforms skew.
Now rotate the child transform using the rotation slider, not how the child transform skews.

**Comment by b005t3r** [comment]
But that's the expected behaviour, isn't it? The parent's scaleX is 3, so it's 3 times wider. When rotated it does not skew and I think it shouldn't (would such behaviour be of any use?), but it's children will, because they local space is stretched along the x-axis.

**Comment by robsilv** [comment]
Yes, you're right.. Seemed odd to me because I'm used to the old system!
