### ISSUE TITLE
Transform2D branch: Nesting transforms (editor?) dragging issue

### ISSUE THREAD

**Issue by robsilv** [CadetEditor/CadetEngine-as#11]
In the editor, create 2 rectangle components.
Now nest the second within the first.
Drag the child rectangle around using the selection tool, note how the position of the rectangle remains the same, relative to the mouse.
Now set the scaleX of the parent rectangle to 3.
Drag the child rectangle around using the selection tool, note how the position of the rectangle doesn't remain the same, relative to the mouse.

**Comment by b005t3r** [comment]
Same issue as this one probably: https://github.com/CadetEditor/CadetEngine-as/issues/9 and https://github.com/CadetEditor/CadetEngine-as/issues/8. They are all caused by the editor not making a conversion between global and local space.

**Comment by robsilv** [comment]
Ok, will look to resolve this in the editor transform2D branch. Thanks!
