### ISSUE TITLE
Box2D conflict

### ISSUE THREAD

**Issue by ulasbinici** [CadetEditor/CadetEngine-as#16]
Which Box2d version are you using ?
i downloaded from www.box2dflash.org/download (Box2DFlash 2.1a)
but in The cadet2DBox2D.components.behaviours.RigidBodyBehaviour 
Box2D.Collision.Shapes.b2CircleDef;
Box2D.Collision.Shapes.b2FilterData etc doenst exist 

Note: i can change import path but there is also missing methods in Box2D b2Body class.

**Comment by robsilv** [comment]
Hi,
I'm not sure how to check, but think it's around 1.4ish. You can find the older versions here:
http://sourceforge.net/projects/box2dflash/files/box2dflash/

**Comment by ulasbinici** [comment]
Thank for replay. i'll check
