### ISSUE TITLE
Can not find swc

### ISSUE THREAD

**Issue by ArmorBearerSlave** [CadetEditor/CadetEngine-as#5]
I can not find CadetEngine.swc.  Where can they be located in the downloaded files?

Eric

**Comment by robsilv** [comment]
Hi Eric,

The bin folders and compiled swcs for the projects aren't included in the github repositories, you need to open the projects in Flash Builder (or similar) and build them to produce these. It's fairly common for derived files to be left out in this way (Away3D does the same, for instance), as these files can often be cleaned and overwritten in a way that doesn't really represent a change to the system.

Hope that helps!

Cheers
Rob

**Comment by ArmorBearerSlave** [comment]
Oh, okay thanks.

One more thing I can not seem to get CadetEditor to save files to locations that are different from the default location.  Any suggestions?

**Comment by robsilv** [comment]
This sounds like the bug with the FileSystemProvider on Mac. This is a known issue and will be fixed in the next editor update (already working locally). Will try to get the next version out soon!

**Comment by ArmorBearerSlave** [comment]
Thanks, look forward to the next edition.

Eric
