### ISSUE TITLE
Type Declaration

### ISSUE THREAD

**Issue by ArmorBearerSlave** [CadetEditor/CadetEngine-as#6]
Renderer2D.as in "cadet2D.components.renderers.Renderer2D; " has a warning on line 87

Type 1008: parameter 'name' has no type declaration.    

Renderer2D.as  
/CadetHelloWorld/[source path] cadet2D-src/cadet2D/components/renderers 
line 87 
Flex Problem

Eric

**Comment by robsilv** [comment]
Thanks Eric,

Fixed [here](https://github.com/CadetEditor/CadetEngine-as/commit/caa06c6076a87d6ea370d05dfd62d0de6e8635da). Not sure why these warnings aren't appearing in my setup... Let me know if you spot any others.

Cheers
Rob
