### ISSUE TITLE
ValidationEvent

### ISSUE THREAD

**Issue by ArmorBearerSlave** [CadetEditor/CadetEngine-as#7]
Hello,

When trying to draw the shaded circle I could not get the shaded circle to show up.  I was able to get it to work when I did the following:

I changed
"import cadet.events.InvalidationEvent;"
to
"import cadet.events.ValidationEvent;"
and all references to it:

if ( _circle )
            {
                _circle.removeEventListener(ValidationEvent.INVALIDATE, invalidateCircleHandler);
            }

```
        _circle = value;

        if ( _circle )
        {
            _circle.addEventListener(ValidationEvent.INVALIDATE, invalidateCircleHandler);
        }

        invalidate("display");
    }
    public function get circle():CircleGeometry{ return _circle; }


    private function invalidateCircleHandler( event:ValidationEvent ):void
    {
```

**Comment by robsilv** [comment]
Thanks for the heads up, I've recently renamed InvalidationEvent to ValidationEvent and forgot to update the wiki. I've updated [that page](https://github.com/CadetEditor/CadetEngine-as/wiki/C2D-06-Writing-your-own-Skin) now, please let me know if you spot any further issues.

**Comment by ArmorBearerSlave** [comment]
Sure will!
