### ISSUE TITLE
Transform2D branch: Nesting transforms dragging issue

### ISSUE THREAD

**Issue by robsilv** [CadetEditor/CadetEngine-as#9]
In the editor, create 2 rectangle components.
Now nest the second within the first.
Select the first rectangle with the selection tool and drag it around, the position of the second rectangle drifts, relative to the first.

**Comment by b005t3r** [comment]
SImilar problem to this one: https://github.com/CadetEditor/CadetEngine-as/issues/8

It looks like editor modifies all Transform2Ds in the selected hierarchy, where it should only modify the first one. It also does not work correctly when moving an object inside a parent, when this parent is scaled or rotated.

**Comment by robsilv** [comment]
Hmm, ok. This sounds like it's due to the editor presuming that all the transforms are at the same level... I obviously need to update the logic to handle this new idea.
